#!/bin/bash
nNodes=1
# nCores=$((68*$nNodes))
nCores=$((12*$nNodes))

fInput='charles.in'
fLog='log.charles'

mpiexec -n $nCores ./charles.exe | tee $fLog
# mpiexec -n $nCores ./charles.exe -i $fInput | tee $fLog

