#!/bin/bash
nNodes=1
# nCores=$((68*$nNodes))
nCores=$((12*$nNodes))

# fInput='charles_init.in'
# fLog='log.init'

fInput='charles.in'
fLog='log.charles'

# /home/yunjaeh/Codes/nextgen/bin
mpiexec -n $nCores ./charles.exe -i $fInput | tee $fLog


