#!/bin/bash
nNodes=1
# nCores=$((68*$nNodes))
nCores=$((12*$nNodes))

fInput='charles_post.in'
fLog='log.charles_post'

mpiexec -n $nCores ./charles.exe -i $fInput | tee $fLog
# mpiexec -n $nCores ./charles.exe -i $fInput | tee $fLog

