#!/bin/bash
nNodes=2
nCores=$((68*$nNodes))
# nCores=$((12*$nNodes))

fInput='charles.in'
fLog='log.test'

mpiexec -n $nCores ./charles.exe -i $fInput | tee $fLog
# mpiexec -n $nCores ./charles.exe -i $fInput | tee $fLog

