#!/bin/bash
nNodes=4
nCores=$((68*$nNodes))
# nCores=$((12*$nNodes))

fInput='charles_coarse2.in'
fLog='log.init2'

mpiexec -n $nCores ../charles.exe -i $fInput | tee $fLog
# mpiexec -n $nCores ./charles.exe -i $fInput | tee $fLog

